// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FizzBuzz.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FizzBuzzFeature : object, Xunit.IClassFixture<FizzBuzzFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "FizzBuzz.feature"
#line hidden
        
        public FizzBuzzFeature(FizzBuzzFeature.FixtureData fixtureData, FizzBuzz_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "FizzBuzz", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Print numbers from 1 to 15 with FizzBuzz rules")]
        [Xunit.TraitAttribute("FeatureTitle", "FizzBuzz")]
        [Xunit.TraitAttribute("Description", "Print numbers from 1 to 15 with FizzBuzz rules")]
        public void PrintNumbersFrom1To15WithFizzBuzzRules()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Print numbers from 1 to 15 with FizzBuzz rules", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
    testRunner.Given("I have a FizzBuzz game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 5
    testRunner.When("I print numbers from 1 to 15", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "header"});
                table1.AddRow(new string[] {
                            "1"});
                table1.AddRow(new string[] {
                            "2"});
                table1.AddRow(new string[] {
                            "Fizz"});
                table1.AddRow(new string[] {
                            "4"});
                table1.AddRow(new string[] {
                            "Buzz"});
                table1.AddRow(new string[] {
                            "Fizz"});
                table1.AddRow(new string[] {
                            "7"});
                table1.AddRow(new string[] {
                            "8"});
                table1.AddRow(new string[] {
                            "Fizz"});
                table1.AddRow(new string[] {
                            "Buzz"});
                table1.AddRow(new string[] {
                            "11"});
                table1.AddRow(new string[] {
                            "Fizz"});
                table1.AddRow(new string[] {
                            "13"});
                table1.AddRow(new string[] {
                            "14"});
                table1.AddRow(new string[] {
                            "FizzBuzz"});
#line 6
    testRunner.Then("I should see the following output:", ((string)(null)), table1, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Print numbers from 1 to 20 with FizzBuzz rules")]
        [Xunit.TraitAttribute("FeatureTitle", "FizzBuzz")]
        [Xunit.TraitAttribute("Description", "Print numbers from 1 to 20 with FizzBuzz rules")]
        public void PrintNumbersFrom1To20WithFizzBuzzRules()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Print numbers from 1 to 20 with FizzBuzz rules", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 25
    testRunner.Given("I have a FizzBuzz game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 26
    testRunner.When("I print numbers from 1 to 20", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "header"});
                table2.AddRow(new string[] {
                            "1"});
                table2.AddRow(new string[] {
                            "2"});
                table2.AddRow(new string[] {
                            "Fizz"});
                table2.AddRow(new string[] {
                            "4"});
                table2.AddRow(new string[] {
                            "Buzz"});
                table2.AddRow(new string[] {
                            "Fizz"});
                table2.AddRow(new string[] {
                            "7"});
                table2.AddRow(new string[] {
                            "8"});
                table2.AddRow(new string[] {
                            "Fizz"});
                table2.AddRow(new string[] {
                            "Buzz"});
                table2.AddRow(new string[] {
                            "11"});
                table2.AddRow(new string[] {
                            "Fizz"});
                table2.AddRow(new string[] {
                            "13"});
                table2.AddRow(new string[] {
                            "14"});
                table2.AddRow(new string[] {
                            "FizzBuzz"});
                table2.AddRow(new string[] {
                            "16"});
                table2.AddRow(new string[] {
                            "17"});
                table2.AddRow(new string[] {
                            "Fizz"});
                table2.AddRow(new string[] {
                            "19"});
                table2.AddRow(new string[] {
                            "Buzz"});
#line 27
    testRunner.Then("I should see the following output:", ((string)(null)), table2, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                FizzBuzzFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                FizzBuzzFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
